# Generated by Django 5.2.1 on 2025-08-12 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('setting', models.CharField(max_length=200)),
                ('culprit_id_hidden', models.CharField(max_length=10)),
                ('difficulty', models.CharField(default='medium', max_length=10)),
                ('num_suspects', models.PositiveSmallIntegerField(default=5)),
                ('num_clues', models.PositiveSmallIntegerField(default=8)),
                ('num_red_herrings', models.PositiveSmallIntegerField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=240)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clues', to='game.case')),
            ],
        ),
        migrations.CreateModel(
            name='ClueImplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suspect_sid', models.CharField(max_length=10)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='implications', to='game.case')),
                ('clue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='implicates', to='game.clue')),
            ],
        ),
        migrations.CreateModel(
            name='RedHerring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.CharField(max_length=10)),
                ('text', models.CharField(max_length=200)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red_herrings', to='game.case')),
            ],
        ),
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=60)),
                ('bio', models.CharField(max_length=220)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspects', to='game.case')),
            ],
        ),
    ]
