# Generated by Django 5.2.1 on 2025-08-12 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('seed', models.CharField(help_text='Random seed for case generation', max_length=100)),
                ('timeline', models.JSONField(default=dict, help_text='Timeline of events in JSON format')),
                ('status', models.CharField(choices=[('active', 'Active'), ('solved', 'Solved'), ('unsolved', 'Unsolved'), ('archived', 'Archived')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('traits', models.JSONField(default=dict, help_text='Character traits in JSON format')),
                ('motive', models.TextField()),
                ('is_culprit', models.BooleanField(default=False)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspects', to='game.case')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='culprit_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='culprit_cases', to='game.suspect'),
        ),
    ]
